import type { ThemeConfigV2, ProjectManifest } from '../types/index.js';

export class ThemeGenerator {
  /**
   * Generates global.design.md file content.
   */
  static generateGlobalDesignMd(manifest: ProjectManifest, theme: ThemeConfigV2): string {
    const now = new Date().toISOString();
    return `# Design System Specification: ${manifest.name}

> Generated by X Design System Studio on ${now}  
> Project Slug: \`${manifest.slug}\`  
> Active Theme: **${theme.name}** (v${theme.version})

---

## 1. Project Overview
- **Name**: ${manifest.name}
- **Description**: ${manifest.description || 'No description provided.'}
- **Creation Source**: \`${manifest.creationSource.type}\`${manifest.creationSource.source ? ` (${manifest.creationSource.source})` : ''}


---

## 2. Core Brand & Palette
- **Personality**: ${theme.personality}
- **Category**: ${theme.category}
- **Font Family**: ${theme.typography.fontName} (\`${theme.typography.fontFamily}\`)

### Primary Colors
| Slot | Hex Code | Gradient Configured |
| :--- | :--- | :--- |
| Background | \`${theme.colors.bg.hex}\` | ${theme.colors.bg.gradient ? 'Yes' : 'No (Flat)'} |
| Primary | \`${theme.colors.primary.hex}\` | ${theme.colors.primary.gradient ? 'Yes' : 'No (Flat)'} |
| Secondary | \`${theme.colors.secondary.hex}\` | ${theme.colors.secondary.gradient ? 'Yes' : 'No (Flat)'} |
| Accent | \`${theme.colors.accent.hex}\` | ${theme.colors.accent.gradient ? 'Yes' : 'No (Flat)'} |

---

## 3. Storage & Architecture
This project is stored using standard file-system semantics in \`.x-design-system/\`.
All tokens inherit via the **Global → Page → Component → PageRef** 4-tier chain.
`;
  }

  /**
   * Generates global.preview.html file content.
   */
  static generateGlobalPreviewHtml(manifest: ProjectManifest, theme: ThemeConfigV2): string {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${manifest.name} — Global Theme Preview</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="${theme.typography.fontGoogleUrl}" rel="stylesheet">
  <style>
    :root {
      --theme-bg: ${theme.colors.bg.hex};
      --theme-primary: ${theme.colors.primary.hex};
      --theme-secondary: ${theme.colors.secondary.hex};
      --theme-accent: ${theme.colors.accent.hex};
      --theme-card-bg: ${theme.colors.surface.hex};
      --theme-card-border: ${theme.colors.surfaceBorder.hex};
      --theme-text-color: ${theme.colors.text.hex};
      --theme-muted-text: ${theme.colors.textMuted.hex};
      --theme-badge-bg: ${theme.colors.badge.bg.hex};
      --theme-badge-border: ${theme.colors.badge.border.hex};
      --theme-badge-text: ${theme.colors.badge.text.hex};
      --theme-hero-glow1: ${theme.colors.glow.primary.hex};
      --theme-hero-glow2: ${theme.colors.glow.secondary.hex};
      --theme-success: ${theme.colors.semantic.success.hex};
      --theme-warning: ${theme.colors.semantic.warning.hex};
      --theme-error: ${theme.colors.semantic.error.hex};
      --font-family: ${theme.typography.fontFamily};
    }

    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      background-color: var(--theme-bg);
      color: var(--theme-text-color);
      font-family: var(--font-family);
      padding: 2rem;
      min-height: 100vh;
    }
    .header { margin-bottom: 2rem; }
    .badge {
      display: inline-block;
      padding: 0.25rem 0.75rem;
      background: var(--theme-badge-bg);
      color: var(--theme-badge-text);
      border: 1px solid var(--theme-badge-border);
      border-radius: 9999px;
      font-size: 0.85rem;
      font-weight: 600;
      margin-bottom: 1rem;
    }
    .title { font-size: 2.5rem; font-weight: 800; margin-bottom: 0.5rem; }
    .subtitle { color: var(--theme-muted-text); font-size: 1.1rem; }
    .color-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(180px, 1fr));
      gap: 1rem;
      margin-top: 2rem;
    }
    .color-swatch {
      padding: 1.25rem;
      background: var(--theme-card-bg);
      border: 1px solid var(--theme-card-border);
      border-radius: 10px;
    }
    .color-box {
      height: 60px;
      border-radius: 6px;
      margin-bottom: 0.75rem;
    }
  </style>
</head>
<body>
  <div class="header">
    <span class="badge">${theme.category} / ${theme.personality}</span>
    <h1 class="title">${manifest.name}</h1>
    <p class="subtitle">${manifest.description || 'Global Theme Design Preview'}</p>
  </div>

  <h2>Global Color Tokens</h2>
  <div class="color-grid">
    <div class="color-swatch">
      <div class="color-box" style="background: var(--theme-primary);"></div>
      <strong>Primary</strong>
      <p style="font-size: 0.85rem; color: var(--theme-muted-text);">${theme.colors.primary.hex}</p>
    </div>
    <div class="color-swatch">
      <div class="color-box" style="background: var(--theme-secondary);"></div>
      <strong>Secondary</strong>
      <p style="font-size: 0.85rem; color: var(--theme-muted-text);">${theme.colors.secondary.hex}</p>
    </div>
    <div class="color-swatch">
      <div class="color-box" style="background: var(--theme-accent);"></div>
      <strong>Accent</strong>
      <p style="font-size: 0.85rem; color: var(--theme-muted-text);">${theme.colors.accent.hex}</p>
    </div>
    <div class="color-swatch">
      <div class="color-box" style="background: var(--theme-card-bg); border: 1px solid var(--theme-card-border);"></div>
      <strong>Surface</strong>
      <p style="font-size: 0.85rem; color: var(--theme-muted-text);">${theme.colors.surface.hex}</p>
    </div>
  </div>
</body>
</html>`;
  }
}
